---
- name: Install dependencies for Grafana Alloy repository
  ansible.builtin.dnf:
    name:
      - gpg
      - curl
    state: present

- name: Create Grafana yum repo
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/grafana.repo
    owner: root
    group: root
    mode: "0644"
    content: |
      [grafana]
      name=grafana
      baseurl=https://rpm.grafana.com
      repo_gpgcheck=1
      enabled=1
      gpgcheck=1
      gpgkey=https://rpm.grafana.com/gpg.key
      sslverify=1
      sslcacert=/etc/pki/tls/certs/ca-bundle.crt

- name: Install Grafana Alloy
  ansible.builtin.dnf:
    name: alloy
    state: present

- name: Render Alloy config
  ansible.builtin.template:
    src: config.alloy.j2
    dest: /etc/alloy/config.alloy
    owner: root
    group: root
    mode: "0644"
  notify: restart alloy

- name: Ensure Alloy is enabled and running
  ansible.builtin.systemd:
    name: alloy
    enabled: true
    state: started
