---
- name: Install MaxScale
  ansible.builtin.dnf:
    name: maxscale
    state: present

- name: Ensure firewalld is enabled and running on maxscale
  ansible.builtin.systemd:
    name: firewalld
    enabled: true
    state: started

- name: Deploy MaxScale config
  ansible.builtin.template:
    src: maxscale.cnf.j2
    dest: /etc/maxscale.cnf
    owner: root
    group: root
    mode: "0644"
  notify: restart maxscale

- name: Allow MaxScale listener on DB zone
  ansible.posix.firewalld:
    zone: "{{ db_zone }}"
    port: "{{ maxscale_rw_port }}/tcp"
    permanent: true
    immediate: true
    state: enabled

- name: Ensure MaxScale is enabled and started
  ansible.builtin.systemd:
    name: maxscale
    enabled: true
    state: started

- name: Reload MaxScale service
  ansible.builtin.command: maxctrl reload service glpi-service
  changed_when: false
