all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/ansible_lab

  children:
    admin_nat:
      hosts:
        admin-nat:
          ansible_host: 192.168.164.1

    haproxies:
      hosts:
        haproxy:
          ansible_host: 192.168.164.10

    web:
      hosts:
        web1:
          ansible_host: 192.168.164.20
        web2:
          ansible_host: 192.168.164.21

    db:
      hosts:
        db1:
          ansible_host: 192.168.164.30
        db2:
          ansible_host: 192.168.164.31

    maxscales:
      hosts:
        maxscale:
          ansible_host: 192.168.164.40
