all:
  vars:
    ansible_user: root
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3

  children:
    active_infra:
      children:
        admin_nodes:
        load_balancers:
        database_cluster:
        database_proxies:
        container_hosts:

    legacy_offline:
      hosts:
        web1:
          ansible_host: 192.168.164.20
          mgmt_ip: 192.168.164.20
          app_ip: 192.168.165.20
          db_ip: 192.168.166.20
          mgmt_interface: ens192
          app_interface: ens224
          db_interface: ens256
          mgmt_zone: internal
          app_zone: dmz
          db_zone: db
          lifecycle_state: offline_legacy

        web2:
          ansible_host: 192.168.164.21
          mgmt_ip: 192.168.164.21
          app_ip: 192.168.165.21
          db_ip: 192.168.166.21
          mgmt_interface: ens192
          app_interface: ens224
          db_interface: ens256
          mgmt_zone: internal
          app_zone: dmz
          db_zone: db
          lifecycle_state: offline_legacy

    admin_nodes:
      hosts:
        admin-nat:
          ansible_host: 192.168.164.1
          mgmt_ip: 192.168.164.1
          public_ip: 172.24.133.165

    load_balancers:
      hosts:
        haproxy:
          ansible_host: 192.168.164.10
          mgmt_ip: 192.168.164.10
          app_ip: 192.168.165.10
          public_ip: 172.24.133.166
          public_vip: 172.24.133.164
          public_interface: ens192
          mgmt_interface: ens224
          app_interface: ens256
          public_zone: public
          mgmt_zone: internal
          app_zone: dmz

    database_cluster:
      hosts:
        db1:
          ansible_host: 192.168.164.30
          mgmt_ip: 192.168.164.30
          db_ip: 192.168.166.30

        db2:
          ansible_host: 192.168.164.31
          mgmt_ip: 192.168.164.31
          db_ip: 192.168.166.31

    database_proxies:
      hosts:
        maxscale:
          ansible_host: 192.168.164.40
          mgmt_ip: 192.168.164.40
          db_ip: 192.168.166.40
          mgmt_zone: internal
          db_zone: db

    container_hosts:
      hosts:
        ctr-host1:
          ansible_host: 192.168.164.60
          mgmt_ip: 192.168.164.60
          app_ip: 192.168.165.60
          db_ip: 192.168.166.60
          mgmt_interface: ens192
          app_interface: ens224
          db_interface: ens256
          mgmt_zone: internal
          app_zone: dmz
          db_zone: db
